# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: todo # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

# you can overwrite defaults here
  stage: dev
  region: ap-southeast-1
  vpc:
    securityGroupIds:
      - sg-007fb2d49786a39eb
    subnetIds:
      - subnet-09834b50
      - subnet-f5485592
      - subnet-15f0f25c

  environment:
    CONNECTION_STRING: ${ssm:dbConnectionString}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  getAllTodos:
    handler: bin/getAllTodos
    events:
      - http:
          path: todo
          method: get
    memorySize: 512

  getTodoWithID:
    handler: bin/getTodoWithID
    events:
      - http:
          path: todo/{id}
          method: get
    memorySize: 512

  insertTodo:
    handler: bin/insertTodo
    events:
      - http:
          path: todo
          method: post
    memorySize: 512

  deleteTodoWithID:
    handler: bin/deleteTodoWithID
    events:
      - http:
          path: todo/{id}
          method: delete
    memorySize: 512

  deleteAll:
    handler: bin/deleteAll
    events:
      - http:
          path: todo
          method: delete
    memorySize: 512

plugins:
  - serverless-sam
